"""
Markdown报告生成器
"""
from typing import List
from datetime import datetime
from pathlib import Path

from app.models.vulnerability import ScanResult, Vulnerability


def generate_markdown_report(scan_result: ScanResult, output_dir: str = "data/reports") -> str:
    """生成Markdown报告"""
    
    md_content = f"""# Web漏洞扫描报告

## 基本信息

- **扫描ID**: {scan_result.scan_id}
- **目标URL**: {scan_result.target_url}
- **开始时间**: {scan_result.start_time.strftime("%Y-%m-%d %H:%M:%S")}
- **结束时间**: {scan_result.end_time.strftime("%Y-%m-%d %H:%M:%S") if scan_result.end_time else "进行中"}
- **状态**: {scan_result.status}

## 漏洞统计

| 严重程度 | 数量 |
|---------|------|
| 高危     | {scan_result.summary.get('high', 0)} |
| 中危     | {scan_result.summary.get('medium', 0)} |
| 低危     | {scan_result.summary.get('low', 0)} |
| **总计** | **{len(scan_result.vulnerabilities)}** |

## 漏洞列表

| 严重程度 | 漏洞名称 | 位置 | 状态 |
|---------|---------|------|------|
"""
    
    for vuln in scan_result.vulnerabilities:
        md_content += f"| {vuln.severity} | {vuln.name} | {vuln.location} | {vuln.status} |\n"
    
    md_content += "\n## 漏洞详情\n"
    
    for i, vuln in enumerate(scan_result.vulnerabilities, 1):
        md_content += f"""
### {i}. {vuln.name}

- **严重程度**: {vuln.severity}
- **位置**: {vuln.location}
- **描述**: {vuln.description}
- **修复建议**: {vuln.remediation}
- **状态**: {vuln.status}
"""
        
        if vuln.poc:
            md_content += f"""
**POC**:

```
{vuln.poc}
```
"""
    
    md_content += f"""
---

*Generated by Web漏洞扫描系统 v1.0.0*  
*Report generated at: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
    
    # 保存报告
    output_path = Path(output_dir) / f"{scan_result.scan_id}.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(md_content, encoding='utf-8')
    
    return str(output_path)
